install-ip now checks for golang compiler errors.

diff --git a/install-ip b/install-ip
--- a/install-ip
+++ b/install-ip
@@ -5,27 +5,27 @@
 ## create the server directory structure and populate it
 ## build the binary into the web site directory and rename it
 
-## Create a golang source file with a constant string containing the time this script ran,
-## and presumably the time the golang source was compiled.
 
+
+## Create a golang source file with a constant string containing the time this script ran.
+## Presumably this will also be the time the golang source was compiled.
 export GOPATH=`pwd`
-echo $GOPATH
 DATE=$(date -u)
-echo "// Programatically generated by install-ip" >$GOPATH/src/date_constant/date_constant.go
-echo "package date_constant" >>$GOPATH/src/date_constant/date_constant.go
-echo "const (DATE string = \"$DATE\")" >> $GOPATH/src/date_constant/date_constant.go
+echo "// Programatically generated by install-ip" > $GOPATH/src/compile_time/compile_time.go
+echo "package compile_time"                       >> $GOPATH/src/compile_time/compile_time.go
+echo "const (DATE string = \"$DATE\")"            >> $GOPATH/src/compile_time/compile_time.go
 ######################################################################################
 
 CONF_FILE=conf/ipgo.conf
 
+echo ----- READ THIS CAREFULLY -----
 [ -f $CONF_FILE ] || { echo cannot find config file: $CONF_FILE; echo exiting; exit 0; }
+[ -f $CONF_FILE ] && { echo reading configuration from: $CONF_FILE; }
 
 # Read the website_directory and website_url settings from the config file.
 while read opt val;
 do
     if [ "$opt" = "website_directory" ]; then
-        # val="${val%\"}";
-        # val="${val#\"}";
         WEBSITE_DIRECTORY=$val
     fi
     if [ "$opt" = "website_url" ]; then
@@ -33,9 +33,8 @@ do
     fi
 done < $CONF_FILE
 
-echo ----- READ THIS CAREFULLY -----
-echo installing to $WEBSITE_DIRECTORY
-echo using url $WEBSITE_URL
+echo installing to:" $WEBSITE_DIRECTORY"
+echo using url:"     $WEBSITE_URL"
 echo "continue? (y/N)"
 
 read -rsn1 c
@@ -51,7 +50,20 @@ mkdir -p $WEBSITE_DIRECTORY/images
 mkdir -p $WEBSITE_DIRECTORY/html
 mkdir -p $WEBSITE_DIRECTORY/conf
 
-go build -o ${WEBSITE_DIRECTORY}/bin/ip.cgi  src/ip.go
+
+## Build the binary into the website location. Exit if there is a compiler erro.
+
+src_file=src/ip.go
+output=$(go build -o ${WEBSITE_DIRECTORY}/bin/ip.cgi  ${src_file} 2>&1)
+
+## If the compiler prints out a line with the source file name in it, there was likely an error.
+grep  -i ${src_file} <<< $output
+if [ $? -eq 0 ]; then
+    echo "Golang detected a compilation error."; echo "Not installing."; exit 1 
+fi
+
+## Install the website files.
+
 install -m644 css/ip.css ${WEBSITE_DIRECTORY}/css/
 install -m644 images/background.png ${WEBSITE_DIRECTORY}/images/
 install -m644 html/ip.html ${WEBSITE_DIRECTORY}/html/
